#include <EngineRuntime.h>

ENGINE_REFLECTED_CLASS(FairBlurInput, Engine::Reflection::Reflected)
	ENGINE_DEFINE_REFLECTED_PROPERTY(INTEGER, Width);
	ENGINE_DEFINE_REFLECTED_PROPERTY(INTEGER, Height);
	ENGINE_DEFINE_REFLECTED_ARRAY(UINT32, Pixel);
	ENGINE_DEFINE_REFLECTED_PROPERTY(DOUBLE, Sigma);
	ENGINE_DEFINE_REFLECTED_PROPERTY(BOOLEAN, AllowMigration);
ENGINE_END_REFLECTED_CLASS